// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class fkaddedtocategorytable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fkaddedtocategorytable));
        
        string IMigrationMetadata.Id
        {
            get { return "202204252309168_fk added to category table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
