// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addedrequiredvalidationtosomecolumns : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedrequiredvalidationtosomecolumns));
        
        string IMigrationMetadata.Id
        {
            get { return "202204252248452_added required validation to some columns"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
